-- Generated locally; not applied to any database.
CREATE TYPE "Front" AS ENUM ('CCPA', 'CASADOTE', 'CED');
CREATE TABLE "Species" ("id" TEXT NOT NULL, "name" TEXT NOT NULL, "createdAt" TIMESTAMP(3) NOT NULL DEFAULT CURRENT_TIMESTAMP, "updatedAt" TIMESTAMP(3) NOT NULL, "deletedAt" TIMESTAMP(3), CONSTRAINT "Species_pkey" PRIMARY KEY ("id"));
CREATE TABLE "Breed" ("id" TEXT NOT NULL, "name" TEXT NOT NULL, "speciesId" TEXT NOT NULL, CONSTRAINT "Breed_pkey" PRIMARY KEY ("id"));
CREATE TABLE "Unit" ("id" TEXT NOT NULL, "name" TEXT NOT NULL, "createdAt" TIMESTAMP(3) NOT NULL DEFAULT CURRENT_TIMESTAMP, "updatedAt" TIMESTAMP(3) NOT NULL, "deletedAt" TIMESTAMP(3), CONSTRAINT "Unit_pkey" PRIMARY KEY ("id"));
CREATE TABLE "Location" ("id" TEXT NOT NULL, "name" TEXT NOT NULL, "unitId" TEXT NOT NULL, CONSTRAINT "Location_pkey" PRIMARY KEY ("id"));
CREATE TABLE "Responsible" ("id" TEXT NOT NULL, "name" TEXT NOT NULL, "active" BOOLEAN NOT NULL DEFAULT true, "createdAt" TIMESTAMP(3) NOT NULL DEFAULT CURRENT_TIMESTAMP, "updatedAt" TIMESTAMP(3) NOT NULL, "deletedAt" TIMESTAMP(3), CONSTRAINT "Responsible_pkey" PRIMARY KEY ("id"));
CREATE TABLE "Animal" ("id" TEXT NOT NULL, "name" TEXT, "publicId" TEXT NOT NULL, "speciesId" TEXT NOT NULL, "breedId" TEXT, "unitId" TEXT NOT NULL, "locationId" TEXT NOT NULL, "responsibleId" TEXT NOT NULL, "front" "Front" NOT NULL, "version" INTEGER NOT NULL DEFAULT 1, "createdAt" TIMESTAMP(3) NOT NULL DEFAULT CURRENT_TIMESTAMP, "updatedAt" TIMESTAMP(3) NOT NULL, "deletedAt" TIMESTAMP(3), CONSTRAINT "Animal_pkey" PRIMARY KEY ("id"));
CREATE UNIQUE INDEX "Species_name_key" ON "Species"("name"); CREATE UNIQUE INDEX "Breed_speciesId_name_key" ON "Breed"("speciesId", "name"); CREATE UNIQUE INDEX "Unit_name_key" ON "Unit"("name"); CREATE UNIQUE INDEX "Location_unitId_name_key" ON "Location"("unitId", "name"); CREATE UNIQUE INDEX "Animal_publicId_key" ON "Animal"("publicId"); CREATE INDEX "Animal_name_idx" ON "Animal"("name"); CREATE INDEX "Animal_speciesId_idx" ON "Animal"("speciesId");
ALTER TABLE "Breed" ADD CONSTRAINT "Breed_speciesId_fkey" FOREIGN KEY ("speciesId") REFERENCES "Species"("id") ON DELETE RESTRICT ON UPDATE CASCADE; ALTER TABLE "Location" ADD CONSTRAINT "Location_unitId_fkey" FOREIGN KEY ("unitId") REFERENCES "Unit"("id") ON DELETE RESTRICT ON UPDATE CASCADE; ALTER TABLE "Animal" ADD CONSTRAINT "Animal_speciesId_fkey" FOREIGN KEY ("speciesId") REFERENCES "Species"("id") ON DELETE RESTRICT ON UPDATE CASCADE; ALTER TABLE "Animal" ADD CONSTRAINT "Animal_breedId_fkey" FOREIGN KEY ("breedId") REFERENCES "Breed"("id") ON DELETE SET NULL ON UPDATE CASCADE; ALTER TABLE "Animal" ADD CONSTRAINT "Animal_unitId_fkey" FOREIGN KEY ("unitId") REFERENCES "Unit"("id") ON DELETE RESTRICT ON UPDATE CASCADE; ALTER TABLE "Animal" ADD CONSTRAINT "Animal_locationId_fkey" FOREIGN KEY ("locationId") REFERENCES "Location"("id") ON DELETE RESTRICT ON UPDATE CASCADE; ALTER TABLE "Animal" ADD CONSTRAINT "Animal_responsibleId_fkey" FOREIGN KEY ("responsibleId") REFERENCES "Responsible"("id") ON DELETE RESTRICT ON UPDATE CASCADE;
